"""Build Ask TitoDex's entity catalog and a minimal set of starter props.

No network, descriptions, or service configuration are included. Regenerate
with Pillow available; keep native pixel sprites at their original resolution.
"""

import io
import json
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "flutter/assets/ask_motion"
CATALOG = ROOT / "flutter/lib/features/journey/ask_motion_catalog.dart"
BOOK = "item-sprites/sonias-book.png"
DEFAULT_SPRITES = (
    "poke-ball", "great-ball", "town-map", "sonias-book", "thunder-stone",
    "fire-stone", "water-stone", "oran-berry", "pecha-berry", "leppa-berry",
    "exp-candy-m", "lucky-egg", "egg", "destiny-knot", "ability-capsule",
    "protein", "calcium", "soothe-bell", "potion", "heat-rock", "damp-rock",
    "smooth-rock", "icy-rock", "leftovers",
)


def read_catalog(name):
    return json.loads((ROOT / "data/l10n/zh" / f"{name}.json").read_text("utf-8"))


def dart_string(value):
    return json.dumps(value, ensure_ascii=False).replace("$", r"\$")


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    types = read_catalog("types")
    type_by_zh = {value["nameZh"]: slug for slug, value in types.items()}
    items = {value["slug"]: dict(value) for value in read_catalog("items").values()}
    audit = json.loads((ROOT / "data/dex/item_media_audit_v19.json").read_text("utf-8"))
    bundle_slugs = {row["slug"] for row in audit["items"] if row["iconPresent"]}
    for row in audit["items"]:
        items.setdefault(row["slug"], {"slug": row["slug"], "nameZh": row["nameZh"]})
    for name in (
        "items_core_extra", "items_all_extra", "items_52poke_extra",
        "items_v19_pokeapi_enrichment", "items_v19_enrichment",
        "item_name_overrides_v19",
    ):
        extra = read_catalog(name)
        for key, value in extra.get("itemsBySlug", extra.get("itemsByZhName", {})).items():
            slug = value.get("slug", key)
            items.setdefault(slug, {"slug": slug}).update({
                k: v for k, v in value.items()
                if k in ("nameZh", "nameEn", "category", "categoryEn", "categoryZh")
            })

    item_rows = []
    for slug, value in items.items():
        if not value.get("nameZh"):
            continue
        # Keep canonical item identity: image lookup is now against the Dex
        # bundle/CDN, including items absent from the local artwork checkout.
        asset = f"item-sprites/{slug}.png" if slug in bundle_slugs else BOOK
        item_rows.append([
            value["nameZh"], value.get("nameEn", "").replace("-", " "),
            "berry" if slug.endswith("-berry") else "item", asset,
        ])
    item_rows.append(["剩饭", "", "item", "item-sprites/leftovers.png"])

    # These few props keep every category usable before installing a bundle.
    # All other item art stays in the Dex instead of being duplicated in the APK.
    images = {}
    for slug in DEFAULT_SPRITES:
        source = ROOT / "data/assets/item-sprites" / f"{slug}.png"
        with Image.open(source) as opened:
            image = opened.convert("RGBA")
            # Rolling distance uses the original ball's exact 80% alpha width.
            # Resampling its edge changes that bound by a pixel at this scale.
            if max(image.size) > 54 and slug not in ("poke-ball", "great-ball"):
                image.thumbnail((54, 54), Image.Resampling.LANCZOS)
            stream = io.BytesIO()
            image.save(stream, format="PNG", optimize=True)
            png = stream.getvalue()
        filename = f"{slug}.png"
        images[filename] = png
    for filename, png in images.items():
        (OUTPUT / filename).write_bytes(png)
    # Only generated flat PNGs in this verified output directory are removed.
    for stale in OUTPUT.glob("*.png"):
        if stale.name not in images and stale.resolve().parent == OUTPUT.resolve():
            stale.unlink()

    catalog = {
        "Types": [[value["nameZh"], slug] for slug, value in types.items()],
        "Items": item_rows,
        "Moves": [[value["nameZh"], value.get("nameEn", ""), type_by_zh[value["typeZh"]]]
                  for key, value in read_catalog("moves").items()
                  if int(key) < 10000 and value.get("typeZh") in type_by_zh],
        "Abilities": [[value["nameZh"], value.get("nameEn", "")]
                      for key, value in read_catalog("abilities").items() if int(key) < 10000],
        "Species": [[value["nameZh"], value.get("nameEn", "")]
                    for value in read_catalog("species").values()],
    }
    lines = [
        "// Generated by tools/build_ask_motion_assets.py; do not edit by hand.",
        "// Names, type identities and relative Dex sprite paths only.",
        "// dart format off", "",
    ]
    for name, rows in catalog.items():
        lines.append(f"const askMotionCatalog{name} = <List<String>>[")
        lines.extend("  [" + ", ".join(dart_string(v) for v in row) + "]," for row in rows)
        lines.extend(["];", ""])
    CATALOG.write_text("\n".join(lines), "utf-8")
    print(json.dumps({
        "catalog": {name: len(rows) for name, rows in catalog.items()},
        "bundledSprites": len(images),
        "spriteBytes": sum(len(png) for png in images.values()),
        "catalogBytes": CATALOG.stat().st_size,
    }))


if __name__ == "__main__":
    main()
