#!/usr/bin/env python3
"""Bulk English → Chinese Pokémon location names (manual / official CN)."""

from __future__ import annotations

# Merged into location_zh_resolver via load_location_names_en_zh().
BULK_LOCATION_NAMES_EN_ZH: dict[str, str] = {
    # Sinnoh
    "Oreburgh City": "黑金市",
    "Oreburgh Gate": "黑金闸口",
    "Oreburgh Mine": "黑金炭坑",
    "Valley Windworks": "风露发电厂",
    "Eterna City": "百代市",
    "Eterna Forest": "百代森林",
    "Old Chateau": "森之洋馆",
    "Route 201": "201号道路",
    "Route 202": "202号道路",
    "Route 203": "203号道路",
    "Route 204": "204号道路",
    "Route 205": "205号道路",
    "Route 206": "206号道路",
    "Route 207": "207号道路",
    "Route 208": "208号道路",
    "Route 209": "209号道路",
    "Route 210": "210号道路",
    "Route 211": "211号道路",
    "Route 212": "212号道路",
    "Route 213": "213号道路",
    "Route 214": "214号道路",
    "Route 215": "215号道路",
    "Route 216": "216号道路",
    "Route 217": "217号道路",
    "Route 218": "218号道路",
    "Route 219": "219号道路",
    "Route 220": "220号道路",
    "Route 221": "221号道路",
    "Route 222": "222号道路",
    "Route 223": "223号道路",
    "Route 224": "224号道路",
    "Route 225": "225号道路",
    "Route 226": "226号道路",
    "Route 227": "227号道路",
    "Route 228": "228号道路",
    "Route 229": "229号道路",
    "Route 230": "230号道路",
    "Fuego Ironworks": "钢铁厂",
    "Ravaged Path": "破坏的路径",
    "Maniac Tunnel": "迷途洞窟",
    "Ruin Maniac Cave": "遗迹迷洞穴",
    "Trophy Garden": "自豪的后院",
    "Solaceon Town": "随意镇",
    "Solaceon Ruins": "随意遗迹",
    "Celestic Town": "神和镇",
    "Mt. Coronet": "天冠山",
    "Spear Pillar": "枪之柱",
    "Hall of Origin": "起源之厅",
    "Sendoff Spring": "送行之泉",
    "Turnback Cave": "归来洞",
    "Snowpoint Temple": "雪峰神殿",
    "Lake Verity": "心齐湖",
    "Lake Valor": "立志湖",
    "Lake Acuity": "睿智湖",
    "Valor Lakefront": "立志湖畔",
    "Acuity Lakefront": "睿智湖畔",
    "Verity Lakefront": "心齐湖畔",
    "Great Marsh": "大湿地",
    "Pastoria City": "湿原市",
    "Canalave City": "水脉市",
    "Iron Island": "钢铁岛",
    "Stark Mountain": "严酷山",
    "Fight Area": "战斗区",
    "Survival Area": "生存区",
    "Resort Area": "休闲区",
    "Flower Paradise": "花之乐园",
    "Fullmoon Island": "满月岛",
    "Newmoon Island": "新月岛",
    "Seabreak Path": "破海之路",
    "Distortion World": "毁坏的世界",
    # Hoenn extras
    "Petalburg Woods": "橙华森林",
    "Rusturf Tunnel": "卡绿隧道",
    "Granite Cave": "石之洞窟",
    "Petalburg City": "橙华市",
    "Slateport City": "凯那市",
    "Mauville City": "紫堇市",
    "Fortree City": "茵郁市",
    "Lilycove City": "水静市",
    "Mossdeep City": "绿岭市",
    "Sootopolis City": "琉璃市",
    "Abandoned Ship": "弃船",
    "New Mauville": "新紫堇",
    "Sky Pillar": "天空之柱",
    "Sealed Chamber": "封印之室",
    "Desert Underpass": "沙漠地下通道",
    "Artisan Cave": "工匠之穴",
    "Altering Cave": "变化洞窟",
    "Ancient Tomb": "古代坟墓",
    "Seafloor Cavern": "海底洞窟",
    "Cave of Origin": "觉醒之祠",
    "Meteor Falls": "流星瀑布",
    "Jagged Pass": "凹凸山道",
    "Fiery Path": "烈焰小径",
    "Mt. Pyre": "送神山",
    "Shoal Cave": "浅滩洞穴",
    "Victory Road": "冠军之路",
    "Ever Grande City": "彩幽市",
    # Unova
    "Castelia Sewers": "飞云下水道",
    "Desert Resort": "沙漠镇",
    "Relic Castle": "古代城",
    "Dragonspiral Tower": "龙螺旋之塔",
    "Moor of Icirrus": "雪花湿地",
    "Twist Mountain": "螺旋山",
    "Chargestone Cave": "电气石洞穴",
    "Mistralton Cave": "吹寄洞穴",
    "Wellspring Cave": "泉源洞窟",
    "Pinwheel Forest": "矢车森林",
    "Lostlorn Forest": "迷幻森林",
    "Abundant Shrine": "丰饶神社",
    "Giant Chasm": "巨人洞窟",
    "Unity Tower": "联合塔",
    "Liberty Garden": "自由花园",
    "P2 Laboratory": "P2实验室",
    "Undella Bay": "青海波湾",
    "Celestial Tower": "天堂之塔",
    "Dragonspiral Tower": "龙螺旋之塔",
    "Mystery Dungeon": "神秘洞窟",
    # Kalos
    "Parfum Palace": "巴摩拉宫",
    "Glittering Cave": "闪耀洞窟",
    "Reflection Cave": "镜之洞窟",
    "Tower of Mastery": "精通塔",
    "Lost Hotel": "废弃酒店",
    "Frost Cavern": "冰霜洞窟",
    "Terminus Cave": "终焉之穴",
    "Pokémon Village": "宝可梦村",
    "Azure Bay": "蓝色海湾",
    "Coumarine City": "海翼市",
    "Laverre City": "香薰市",
    "Anistar City": "映雪市",
    "Snowbelle City": "冰雪镇",
    "Kiloude City": "奇楠市",
    # Alola
    "Iki Town": "好奥花市",
    "Hau'oli City": "好奥花市",
    "Heahea City": "慷概市",
    "Paniola Town": "欧雷吉镇",
    "Konikoni City": "阿卡拉岛",
    "Aether Paradise": "以太乐园",
    "Mount Lanakila": "拉纳基拉山",
    "Seafolk Village": "海洋居民村",
    "Tapu Village": "卡璞村",
    "Brooklet Hill": "欧雷吉丘陵",
    "Wela Volcano Park": "维拉火山",
    "Lush Jungle": "密阿雷丛林",
    "Hokulani Observatory": "哈库拉尼天文台",
    "Mount Hokulani": "哈库拉尼山",
    "Thrifty Megamart": "超值超市",
    "Poni Grove": "波尼树林",
    "Poni Plains": "波尼平原",
    "Poni Coast": "波尼海岸",
    "Poni Wilds": "波尼旷野",
    "Ancient Poni Path": "波尼古道",
    "Altar of the Sunne": "日轮祭坛",
    "Altar of the Moone": "月轮祭坛",
    "Resolution Cave": "决议洞窟",
    "Vast Poni Canyon": "波尼大峡谷",
    "Ultra Space": "究极空间",
    # Galar
    "Slumbering Weald": "迷之森林",
    "Glimwood Tangle": "迷光森林",
    "Ballimere Lake": "王冠雪原湖",
    "Freezington": "冻凝村",
    "Snowslide Slope": "降雪坡道",
    "Frigid Sea": "冻海",
    "Three-Point Pass": "三岔平原",
    "Split-Decision Ruins": "抉择遗迹",
    "Giant's Bed": "巨人睡床",
    "Giant's Foot": "巨人脚掌",
    "Giant's Mirror": "巨人镜面",
    "Old Cemetery": "古 cemetery",
    "Watchtower Ruins": "瞭望塔遗迹",
    "Stow-on-Side": "战竞镇",
    "Hammerlocke": "拳关市",
    "Wyndon": "宫门市",
    "Spikemuth": "尖钉镇",
    "Circhester": "战竞镇",
    "Hulbury": "水舟镇",
    "Turffield": "草路镇",
    "Motostoke": "机擎市",
    "Wedgehurst": "化朗镇",
    "Postwick": "化朗镇",
    "Bridge Field": "桥间空地",
    "Brawlers' Cave": "格斗家洞窟",
    "Galar Mine": "伽勒尔矿坑",
    "Galar Mine No. 2": "伽勒尔矿坑2",
    "Dusty Bowl": "沙尘盆地",
    "Lake of Outrage": "愤怒之湖",
    "Axew's Eye": "牙牙之眼",
    "Rolling Fields": "滚轮 fields",
    "East Lake Axewell": "牙牙湖东",
    "West Lake Axewell": "牙牙湖西",
    "North Lake Miloch": "美录湖 north",
    "South Lake Miloch": "美录湖 south",
    "Dappled Grove": "花之草原",
    "Watchtower Ruins": "瞭望塔遗迹",
    "Crown Shrine": "王冠神殿",
    "Dynite Tree Hill": "极巨树 hill",
    # Paldea
    "Mesagoza": "桌台市",
    "Cabo Poco": "深钵镇",
    "Los Platos": "深钵镇",
    "Artazon": "深钵镇",
    "Levincia": "酿光市",
    "Porto Marinada": "玻瓶市",
    "Medali": "酿光市",
    "Montenevera": "霜抹山",
    "Alfornada": "深钵镇",
    "Casseroya Lake": "大锅湖",
    "Area Zero": "第零区",
    "Glaseado Mountain": "霜抹山",
    "North Province Area One": "北1区",
    "South Province Area One": "南1区",
    "East Province Area One": "东1区",
    "West Province Area One": "西1区",
    "Tagtree Thicket": "Tagtree Thicket",
    "Asado Desert": "Asado Desert",
    # Johto / Kanto extras
    "Tin Tower": "铃铛塔",
    "Whirl Islands": "涡旋岛",
    "Cliff Cave": "断崖洞窟",
    "Embedded Tower": "嵌入塔",
    "Safari Zone Gate": "狩猎地带入口",
    "Route 29": "29号道路",
    "Route 30": "30号道路",
    "Route 31": "31号道路",
    "Route 32": "32号道路",
    "Route 33": "33号道路",
    "Route 34": "34号道路",
    "Route 35": "35号道路",
    "Route 36": "36号道路",
    "Route 37": "37号道路",
    "Route 38": "38号道路",
    "Route 39": "39号道路",
    "Route 40": "40号道路",
    "Route 41": "41号道路",
    "Route 42": "42号道路",
    "Route 43": "43号道路",
    "Route 44": "44号道路",
    "Route 45": "45号道路",
    "Route 46": "46号道路",
    "Route 47": "47号道路",
    "Route 48": "48号道路",
    "Cerulean Cave": "华蓝洞窟",
    "Diglett's Cave": "地鼠洞",
    "Rock Tunnel": "岩山隧道",
    "Seafoam Islands": "双子岛",
    "Power Plant": "无人发电厂",
    "Mt. Moon": "月见山",
    "Dark Cave": "黑暗洞窟",
    "Ice Path": "冰雪小径",
    "Dragon's Den": "龙穴",
    "Mt. Mortar": "擂钵山",
    "Union Cave": "连接洞窟",
    "Slowpoke Well": "呆呆兽之井",
    "Ilex Forest": "栎树林",
    "National Park": "自然公园",
    "Bell Tower": "铃铛塔",
    "Burned Tower": "烧焦塔",
    "Ruins of Alph": "阿露福遗迹",
    "Lake of Rage": "愤怒之湖",
    "Mt. Silver": "白银山",
    "Indigo Plateau": "石英联盟",
    # Orre / misc
    "Agate Village": "阿格特村",
    "Gateon Port": "盖欧门港",
    "Phenac City": "芬纳克市",
    "Pyrite Town": "黄铁矿镇",
    "The Under": "地下",
    # Common sub-areas
    "Pokémon Center": "宝可梦中心",
    "Poké Mart": "友好商店",
    "Gym": "道馆",
    "Cave": "洞窟",
    "Forest": "森林",
    "Ruins": "遗迹",
    "Path": "小径",
    "Tunnel": "隧道",
    "Tower": "塔",
    "Lake": "湖",
    "Mountain": "山",
    "Beach": "海滩",
    "Island": "岛",
    # Remaining high-frequency unresolved (2026-07)
    "Friend Safari": "朋友狩猎区",
    "Reversal Mountain": "反转山",
    "Lost Cave": "迷路洞窟",
    "Citadark Isle": "暗之岛",
    "Johto Safari Zone": "城都狩猎地带",
    "Cipher Key Lair": "密键藏身处",
    "Pyrite Cave": "黄铁矿洞窟",
    "Icefall Cave": "冻瀑洞窟",
    "Mirage Island": "幻影岛",
    "Mirage Cave": "幻影洞窟",
    "Mirage Forest": "幻影森林",
    "Mirage Mountain": "幻影山",
    "ONBS": "ONBS",
    "Scorched Slab": "灼热石板",
    "Ultra Space Wilds": "究极空间",
    "Challenger's Cave": "挑战者洞窟",
    "Cipher Lab": "密键研究所",
    "Floccesy Ranch": "唐草牧场",
    "Giant's Cap": "巨人帽岩",
    "Mt. Battle": "战斗山",
    "Mt. Ember": "灯火山",
    "Poké Pelago": "宝可梦度假地",
    "Pokespot": "宝可梦Spot",
    "Relic Passage": "遗迹通道",
    "Sea Mauville": "海上紫堇",
    "Stony Wilderness": "巨石原野",
    "Verdant Cavern": "翠绿洞窟",
    "Dreamyard": "梦之遗迹",
    "Malie City": "马利埃市",
    "Outskirt Stand": "外围站",
    "Pokemon Hq Lab": "宝可梦总部研究所",
    "Pyrite Bldg": "黄铁矿大厦",
    "Realgam Tower": "Realgam塔",
    "Royal Avenue": "皇家大道",
    "Seaside Cave": "海边洞窟",
    "Shadow Pokémon Lab": "黑暗宝可梦研究所",
    "Snagem Hideout": "Snagem藏身处",
    "Stepping-Stone Sea": "垫脚石之海",
    "Strange House": "奇异之屋",
    "Ten Carat Hill": "十克拉山丘",
    "Cape Brink": "布林克角",
    "Bond Bridge": "纽带桥",
    "Three Isle Port": "3岛港口",
    "Resort Gorgeous": "豪华度假地",
    "Water Labyrinth": "水之迷宫",
    "Five Isle Meadow": "5岛原野",
    "Memorial Pillar": "纪念柱",
    "Outcast Island": "流放岛",
    "Altering Cave": "变化洞窟",
    "Monean Chamber": "莫尼安之间",
    "Liptoo Chamber": "利普图之间",
    "Weepth Chamber": "维普夫之间",
    "Dilford Chamber": "迪尔福德之间",
    "Scufib Chamber": "斯库菲布之间",
    "Rixy Chamber": "里克斯之间",
    "Viapos Chamber": "维亚波斯之间",
    "Pokémon Tower": "宝可梦塔",
    "Pokémon Mansion": "宝可梦屋",
    "SS Anne": "圣特安努号",
    "Sea Route 19": "19号水路",
    "Sea Route 20": "20号水路",
    "Sea Route 21": "21号水路",
    "Sea Route 40": "40号水路",
    "Sea Route 41": "41号水路",
    "Sea Route 220": "220号水路",
    "Sea Route 223": "223号水路",
    "Sea Route 226": "226号水路",
    "Sea Route 230": "230号水路",
}
